import '../css/globals.css'

import React from 'react';
import { Inter } from 'next/font/google'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }) {

  const data = {
    animations: true
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        {
          React.cloneElement(children, { data })
        }
      </body>
    </html>
  )
}

export default RootLayout;